name: Pull request

on: [pull_request]

jobs:

  build_and_push_Docker_image:
    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.event.pull_request.head.sha }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - run: go build .

      