name: Pull request

on: [pull_request]

jobs:

  build_and_push_Docker_image:
    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.event.pull_request.head.sha }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.4'
      - run: echo $GOPATH
      - run: dep ensure
      - run: go get -t ./...
      - run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo
      - name: Build onsdigital/eq-schema-validator Docker image
        run: docker build -t onsdigital/eq-schema-validator:$TAG -f Dockerfile .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to onsdigital/eq-schema-validator with $TAG
        run: docker push onsdigital/eq-schema-validator:$TAG
